config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/inbox'
  end
  resources :subscribe_me, only: [:index] do
    post :enviar_email, on: :member
    get :index, on: :member
  end
  resources :respuesta, only: [:new, :create]
  get 'respuesta/complete', to: 'respuesta#complete'
  root to: 'admin/dashboard#index'
end

app/models/respuesta.rb
# == Schema Information
#
# Table name: respuestas
#
#  id                     :bigint           not null, primary key
#  valor_respuesta        :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  cliente_id             :bigint           not null
#  formulario_pregunta_id :bigint           not null
#
# Indexes
#
#  index_respuestas_on_cliente_id              (cliente_id)
#  index_respuestas_on_formulario_pregunta_id  (formulario_pregunta_id)
#
# Foreign Keys
#
#  fk_rails_...  (cliente_id => clientes.id)
#  fk_rails_...  (formulario_pregunta_id => formularios_pregunta.id)
#
class Respuesta < ApplicationRecord
  belongs_to :cliente
  belongs_to :formulario_pregunta
  enum valor_respuesta: %i[good regular bad]

end

app/controllers/respuesta_controller.rb
class RespuestaController < ApplicationController
  before_action :authenticate_user
  def new
    @user = Cliente.find_by(email: session[:current_email])
    # La línea inferior podría mejorarse significativamente, ya que si las encuestas,
    # formularios y preguntas no están creados, estas líneas de código fallarán.
    # Además, sería beneficioso verificar si el usuario ya ha completado la
    # encuesta y, en caso afirmativo, permitirle seleccionar otra encuesta de
    # manera aleatoria, pero asegurándose de que esté relacionada con
    #  las preferencias que el cliente haya marcado previamente. 
    @questions = @user.preferencias.first.encuestas.first.formulario.preguntas
    if session[:current_step].blank?
      session[:current_step]=1
    end
  end
  def create
    @user = Cliente.find_by(email: session[:current_email])
    @questions = @user.preferencias.first.encuestas.first.formulario.preguntas
    formulario_pregunta_id = Pregunta.find(params[:question_id]).formulario_preguntas.first.id
    respuesta = Respuesta.new(
      cliente_id: @user.id,
      formulario_pregunta_id: formulario_pregunta_id,
      valor_respuesta: params[:answer].to_i
    )
    if respuesta.save!
      session[:current_step] += 1
      if session[:current_step] > @questions.count
        CrearCupon.new.run(session[:email])
        redirect_to respuesta_complete_path
      else
        redirect_to new_respuestum_path
      end
    else
      render :new
    end
  end
  private
  def authenticate_user
    @user = Cliente.find_by(email: session[:current_email])
    if @user.nil? == true
      redirect_back(fallback_location: subscribe_me_index_path)
    end 
  end
end

app/views/respuesta/_form.erb
<div class="container-complete">
  <h1> <%= t('questions.step_title') %>  <%= session[:current_step] %></h1>
  <%= form_tag respuesta_path do %>
    <%= hidden_field_tag :question_id, @questions[session[:current_step] - 1].id %>
    <div class="field">
      <%= label_tag 'answer', t("#{@questions[session[:current_step] - 1].texto}") %><br>
  
      <!-- Usar radio_button para cada opción del enum -->
      <%= radio_button_tag 'answer', 'good' %> <%= t('questions.good_option') %>
      <%= radio_button_tag 'answer', 'regular' %> <%= t('questions.regular_option') %>
      <%= radio_button_tag 'answer', 'bad' %> <%= t('questions.bad_option') %>
    </div>
    <%= submit_tag "#{t('questions.submit_button')}"  %>
  <% end %>
  
</div>

app/views/respuesta/complete.html.erb
<div class="container-complete">
  <h1><%= t('survey.completed.title') %></h1>
  <p><%= t('survey.completed.thank_you') %></p>
</div>

app/views/respuesta/new.html.erb
<div class="container-complete">
  <h1> <%= t('questions.step_title') %>  <%= session[:current_step] %></h1>
  <%= form_tag respuesta_path do %>
    <%= hidden_field_tag :question_id, @questions[session[:current_step] - 1].id %>
    <div class="field">
      <%= label_tag 'answer', t("#{@questions[session[:current_step] - 1].texto}") %><br>
  
      <!-- Usar radio_button para cada opción del enum -->
      <%= radio_button_tag 'answer', 'good' %> <%= t('questions.good_option') %>
      <%= radio_button_tag 'answer', 'regular' %> <%= t('questions.regular_option') %>
      <%= radio_button_tag 'answer', 'bad' %> <%= t('questions.bad_option') %>
    </div>
    <%= submit_tag "#{t('questions.submit_button')}"  %>
  <% end %>
  
</div>