config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/inbox'
  end
  resources :subscribe_me, only: [:index] do
    post :enviar_email, on: :member
    get :index, on: :member
  end
  resources :respuesta, only: [:new, :create]
  get 'respuesta/complete', to: 'respuesta#complete'
  root to: 'admin/dashboard#index'
end

app/models/cliente.rb
# == Schema Information
#
# Table name: clientes
#
#  id         :bigint           not null, primary key
#  email      :string
#  nombre     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Cliente < ApplicationRecord
  
  has_many :respuestas
  has_many :cupones
  has_many :cliente_preferencias
  has_many :preferencias, through: :cliente_preferencias
  accepts_nested_attributes_for :preferencias
end

app/controllers/subscribe_me_controller.rb
class SubscribeMeController < ApplicationController
  before_action :load_params, only: :enviar_email
  def index; end

  def enviar_email
    return flash[:alert] = I18n.t('controllers.subscribe_me.email_blank_error') if permit_params[:email].empty?

    if @preferencias_id.empty?
      flash[:alert] = I18n.t('controllers.subscribe_me.no_preference_selected_error')
    else
      handle_email_identification
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def handle_email_identification
    response = IdentificarEmail.new.identificar(permit_params[:email], @preferencias_id)
    session[:current_email] = permit_params[:email] if response['success']
    flash[:alert] = I18n.t('controllers.subscribe_me.email_subscribe_success') if response['success']
    flash[:alert] = I18n.t('controllers.subscribe_me.email_identification_error') unless response['success']
  end

  def load_params
    @preferencias_id = permit_params[:preferencia_ids].reject(&:empty?)
  end

  def permit_params
    params.require(:subscribe).permit(:email, preferencia_ids: [])
  end
end

app/views/subscribe_me/index.html.erb
<% if flash[:alert] %>

<label>
  <input type="checkbox" class="alertCheckbox" autocomplete="off" />
  <div class="alert warning">
    <span class="alertClose">X</span>
    <span class="alertText"><%= flash[:alert] %>
		<br class="clear"/></span>
  </div>
</label>



<% end %>
<div class="container-subscribe">
  <h1 class="block-effect" style="--td: 1.2s">
  
    <div class="block-reveal" style="--bc: #67b884; --d: .1s"><%=  image_tag "logo.svg" %> </div>
    <div class="block-reveal" style="--bc: #040F0F; --d: .5s">
      <div style="display:flex;justify-content:center;align-items:center;">
        <small style="font-size: 1rem;">
        Welcome! Soon we will launch our site in
                    this country.
            Suscribe to receive our newsletter.
            </small>
      </div>
    </div>
  </h1>
  <div class="article-subscribe-me">
  <%= form_for(:subscribe, url: enviar_email_subscribe_me_path, html: { multipart: true,class:"form-subscribe"}) do |f| %>
  
                      <div class="email-subscribe">
                        <%= f.text_field :email,label: 'Email',placeholder:"Email" %>
                      </div>
                      <div class="check-box-subscribe">
                        <%= f.collection_check_boxes :preferencia_ids, Preferencia.all, :id, :texto do |b| %>
                            <div class="row-subscribe"><%= b.label { b.check_box + b.text } %></div>
                        <% end %>
                      </div>
  
                  <div class="submit-subscribe">
                  <%= f.submit %>
                  </div>
              <% if session[:current_email].present? %>
                <div class="submit-subscribe"><%= link_to I18n.t('links.get_coupons'), new_respuestum_path %></div>
              <% end %>
              <% end %>
  </div>
</div>